name: Build Jellyfin Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build & Package Jellyfin Plugin
        uses: oddstr13/jellyfin-plugin-repository-manager@v1.1.1
        id: jprm
        with:
          dotnet-target: "net8.0"

      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-artifact
          path: ${{ steps.jprm.outputs.artifact }}
          retention-days: 30
          if-no-files-found: error

      - name: Show Artifact Download Link
        run: |
          echo "Download your build artifact from:"
          echo "https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"